spring:
  application:
    # 服务名称
    name: my-spring-cloud-eureka

server:
  port: 8083

eureka:
  client:
    # 是否注册自己的信息到EurekaServer
    register-with-eureka: false
    # 是否拉取其它服务的信息，默认是true
    fetch-registry: false
    # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
    service-url:
      defaultZone: http://localhost:8083/eureka/
